name: prides
description: A package that helps in creating custom Slides and Presenting them.
version: 0.0.1
# homepage:
repository: https://github.com/immadisairaj/prides
issue_tracker: https://github.com/immadisairaj/prides/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # This is a package from dart.dev that contains annotations like
  # @internal that is used by the Flutter tool to analyze code.
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # This package is from very good ventures that contains lints
  # for some good practices while writing code.
  very_good_analysis: ^5.0.0
