name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    # A reusable workflow for ensuring commits are semantic
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    # TODO(immadisairaj): Remove this line once initial commits are done
    if: github.event_name != 'push'

  package_scores:
    # A reusable workflow for verifying package scores on pub.dev
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      min_score: 140 # The score should always be maximum
  
  flutter_package:
    # A reusable workflow for Flutter packages
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      min_coverage: 100 # The coverage should always be maximum
